### ISSUE TITLE
Import source tree inside a Nickel package

### ISSUE THREAD

**Issue by yannham** [nickel-lang/nickel-nix#11]
Find a way to import any kind of source tree inside the Nickel part. The simplest example is a source file: in the current version of the future prototype, we have to pass it wrapped as a derivation from the Nix side:

The nickel package:

```
{
  inputs_spec = {
    bash = { input = "nixpkgs" },
    coreutils = { input = "nixpkgs" },
    gcc = { input = "nixpkgs" },
    hello = { input = "sources" },
  }

  , output = fun { inputs, nix, .. } =>
    {
      name = "hello",
      version = "0.1",
      build_command = {
        cmd = "%{inputs.bash.outputPath}/bin/bash",
        args = [ "-c", m%"
          %{inputs.gcc.outputPath}/bin/gcc %{inputs.hello.outputPath} -o hello
          %{inputs.coreutils.outputPath}/bin/mkdir -p $out/bin
          %{inputs.coreutils.outputPath}/bin/cp hello $out/bin/hello
        "%m, ]
      },
      env = {},
      dependencies = [ inputs.bash, inputs.coreutils, inputs.gcc, inputs.hello ],
    } | nix.builders.NickelPkg
}
```

The Nix wrapper:

```nix
        packages.default = importNcl ./hello.ncl (inputs // {
          sources.packages.${system}.hello = pkgs.runCommand "hello.c" {} "cp ${./hello.c} $out";
        });
```

## Ideas

- Use a special placeholder on the Nickel side, that the Nix part
       interpret and substitute for actual store paths
- Have them be just other inputs, and let the Nixel Nix library do the
       work (determine which source trees are coming directly from Nix, and
       which one are coming from other Nickel package definitions)

**Comment by yannham** [comment]
Here is one attempt: https://github.com/nickel-lang/nickel-nix/pull/10/commits/83a6e72e95897828e89c41cf9ee0ae671f49947a. We have to pass the base directory of the flake to `importNcl`, which is not very natural, but otherwise it looks rather natural.

**Comment by thufschmitt** [comment]
Implemented with the `nix.import_file` function
