### ISSUE TITLE
Remove the need for `--impure`

### ISSUE THREAD

**Issue by yannham** [nickel-lang/nickel-nix#15]
The current version of nickel-nix requires `--impure` to run, because Nix loses some information when passing derivations to the Nickel world, and then back from the Nickel world.

@thufschmitt started an attempt (https://github.com/thufschmitt/nickel-nix/tree/nicke-shell-pure), which works, but is ugly. We can work our way from here to a cleaner solution.

**Comment by mkatychev** [comment]
@yannham has there been any progress on this?

**Comment by yannham** [comment]
I don't think there's currently someone looking into this actively. @YorikSar may have a better idea of what's going on currently
