### ISSUE TITLE
Dependencies between Nickel derivations

### ISSUE THREAD

**Issue by thufschmitt** [nickel-lang/nickel-nix#16]
It's currently possible to write a derivation in Nickel, and have that derivation refer to other derivations imported from Nix.
However, we aren't able to express a dependency from one Nickel derivation to another.

The reason for that is the following:

In Nix, the way we express a dependency from `foo` to `bar` is by interpolating `bar` somewhere inside the builder of `foo`. Something like `buildCommand = "${bar}/bin/bar > $out"`. In such an expression, `${bar}` gets coerced to `bar.outPath`, which is indeed the place where it will be found at runtime.

We do essentially [the same thing](https://github.com/nickel-lang/nickel-nix/blob/83a6e72e95897828e89c41cf9ee0ae671f49947a/examples/c-hello-world/hello.ncl#L19-L21) in Nickel for the derivations that we import from Nix.
However, we can't – at least not currently – do the same for the derivations that we define directly in Nickel code. The reason is that these aren't evaluated at all on the Nickel side, we just carry them out symbolically until we pass the control back to Nix. So they don't have a valid `outPath` field, and the following can't work:

```nickel
let
  bar = ... | nix.builders.NickelPkg in
{
  shellHook = "%{bar.outPath}/bin/bar",
} | nix.builders.NickelShell,
```

I can think of different solutions to this problem:

1. Compute `outPath` earlier:
    This means computing it directly when we apply the `NickelPkg` contract, which I guess means either:
    1. Call Nix from Nickel (using a dedicated `eval_nix` builtin or something like that)
    2. Reimplement a pure Nickel version of the `derivation` Nix builtin
2. Defer the actual interpolation to the Nix side:
   Either:
   1. Use some form of templated strings (like Bazel's [Make variables](https://bazel.build/reference/be/make-variables#custom_variables) for example) that will be resolved on the Nix side, or
   2. Keep these string-with-references symbolic, similar to Guix's [`G-expressions`](https://guix.gnu.org/manual/en/html_node/G_002dExpressions.html). Strings would instead be lists (or trees) of chunks, where each chunk is either a plain string or a deferred interpolated expression. This is what [the current prototype of string context](https://github.com/nickel-lang/nickel-nix/blob/83a6e72e95897828e89c41cf9ee0ae671f49947a/examples/c-hello-world-string-ctxt/hello.ncl#L18-L22) does.
3. Don't use string interpolation at all, but rely on another mechanism.
   1. For most rules, Bazel just relies on the fact that the location of the inputs on disk is well-known. We could have a similar thing by having a custom base builder that enforces this;
   2. Alternatively, we could decide that all the location of the inputs have to be passed via a specific mechanism (somewhat similar to Bazel's [`runfiles`](https://bazel.build/rules/lib/runfiles)). That could be as simple as just exposing each of them as an environment variable.

Overall, I would have a preference for 2.2 because it's the cleaner one conceptually speaking, and it also solves the “string context” issue. It also seems like a very generic one that could benefit other Nickel use-cases.
The downsides are that:
1. It can be syntactically heavy, unless we manage to generalize the string interpolation to make it look just like a special case of it;
2. It might also be slower, or at least less memory-efficient than some other mechanisms (_might_, I'm not really sure).

**Comment by aspiwack** [comment]
To give a little bit of extra context for me to understand better what the alternative entail: how is Nix currently invoked? Do we compute a string representing a Nix expression then call Nix on it? Something else?

**Comment by thufschmitt** [comment]
Yeah, that sounds reasonable, and it wouldn't harm to have it written down somewhere.

Technically speaking, Nix is currently not invoked by Nickel, it's the other way around.

We do that by generating a small (mostly static) Nickel shim on the Nix side that imports a serialized (JSON) version of the data we need to exchange and returns a JSON that's deserialized by Nix.

The whole control-flow is currently a two-steps process:
The Nickel file contains two things:
1. A declaration of the inputs it needs (`inputs_spec`)
2. A function taking these inputs and returning the final result (`outputs`)

- Nix will first call Nickel to get the `inputs_spec`, and internally evaluates that to a map `Name -> outPath`
- Then it calls the `outputs` function, passing it this map as argument, and transforms the result to a tree of derivations (using [this encoding](https://github.com/nickel-lang/nickel-nix/blob/83a6e72e95897828e89c41cf9ee0ae671f49947a/lib.nix#L26-L52)

```mermaid
sequenceDiagram
  Nix-->>Nickel: Query the input schema
  Nickel->>Nix: Inputs schema
  Note left of Nix: Resolve the inputs to their output path
  Nix->>Nickel: Resolved inputs
  Note right of Nickel: Evaluate the Nickel expression
  Nickel->>Nix: Symbolic derivation tree
  Note left of Nix: Translate the symbolic tree to derivations
```

All the logic involved in this issue happens during the evaluation of the `outputs` Nickel function, which (currently) has no way of communicating with Nix.

**Comment by thufschmitt** [comment]
Afaik this is possible with symbolic strings now. Closing
