### ISSUE TITLE
Make it possible to depend on a package that's not at toplevel on nixpkgs

### ISSUE THREAD

**Issue by thufschmitt** [nickel-lang/nickel-nix#35]
I wanted to add a dependency to `libcurl` in a C shell. However, that required adding `curl.dev` to my inputs, which currently isn't possible since the input must have the form `inputs.${inputName}.(legacy)Packages.${blah}`. (I worked my way around by editing the Nix code to expose it as `curl_dev`, but that's very hacky)

It would be important to allow accessing nested fields inside an input, maybe by adding an optional `attribute_path | Array String` attribute to the elements of `input_spec`

**Comment by yannham** [comment]
Ah, just had the same issue with a node package (markdownlint-cli) :+1:

**Comment by rapenne-s** [comment]
This may explain some problem I had with the Python devshell :sweat_smile: It may work after this is fixed
