### ISSUE TITLE
devshells are built but not providing anything in PATH

### ISSUE THREAD

**Issue by rapenne-s** [nickel-lang/nickel-nix#50]
https://github.com/nickel-lang/nickel-nix/pull/45 introduced a regression (more precisely https://github.com/nickel-lang/nickel-nix/commit/a664787532287ebf3d7ff97d89afc874b39853c6 thanks to git bisect)

the CI still pass because everything evaluates fine, but the new environment has no package from the dev shell.

**Comment by yannham** [comment]
Should be fixed by #46.
