### ISSUE TITLE
Sane environment variable setup

### ISSUE THREAD

**Issue by balsoft** [nickel-lang/nickel-nix#72]
We want to have a way to "automatically" set the environment variables in the shell, which the user wants, without the user thinking about those variables themselves.

Perhaps, have a `programs` attribute all of which get added to `$PATH`, or integrate with `stdenv/setup.sh` from nixpkgs to set more variables at runtime.

**Comment by happysalada** [comment]
https://github.com/numtide/devshell/tree/main
gives you essential environment variables without giving you all the extra uneeded stuff that are there by default from the default nix shell.
The ideal would be to have just what is needed.
Not sure if the approach is the right one, but he proceeds per shell, (if you do `rust.enable = true` then you get the environment variables that cargo needs.

**Comment by thufschmitt** [comment]
Fixed by #89
